Microservices:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: fatih-steve  
    ImageId: ami-09538990a0c4fe9be
    InstanceType: t2.micro
    SecurityGroupIds: 
      - sg-0b11d6f8871b2871d
    UserData:
      #! /bin/bash
      yum update -y 
      hostnamectl set-hostname microservices-dev-server
      yum install docker -y
      systemctl start docker
      systemctl enable docker
      usermod -a -G docker ec2-user
      curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" \
      -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      yum install git -y
      yum install java-11-amazon-corretto -y
      git clone https://github.com/fatiyildiz/MICROSERVICES-CI-CD-PIPELINE.git
      cd ci-cd-pipeline-microservices
      git fetch
      git checkout dev
    Tags:
      - Key: Name
        Value: microservices